apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ignite
  namespace: dev-02-vizix-cloud
  labels:
    app: ignite
  annotations:
    reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/reload: "ignite-config"
    com.devops.version: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ignite
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ignite
    spec:
      volumes:
        - name: ignite-config
          configMap:
            name: ignite-config
        - name: ignite-disk-dev-02
          persistentVolumeClaim:
            claimName: ignite-disk-dev-02
      # serviceAccountName: ignite
      containers:    
      - name: ignite
        image: apacheignite/ignite:2.7.6
        imagePullPolicy: Always
        env:
          - name: OPTION_LIBS
            value: "ignite-rest-http"
          - name: CONFIG_URI
            value: file:///etc/apache-ignite/config/ignite-config.xml
          - name: IGNITE_QUIET
            value: "false"
          - name: JVM_OPTS
            value: "-server -Xms1g  -Xmx1g -XX:NewSize=512m -XX:SurvivorRatio=6 -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:MaxGCPauseMillis=2000 -XX:GCTimeRatio=4 -XX:InitiatingHeapOccupancyPercent=30 -XX:G1HeapRegionSize=8M -XX:ConcGCThreads=1 -XX:G1HeapWastePercent=10 -XX:+UseTLAB -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC"
        ports:
          - containerPort: 11211 # REST port number.
          - containerPort: 47100 # communication SPI port number.
          - containerPort: 47500 # discovery SPI port number.
          - containerPort: 49112 # JMX port number.
          - containerPort: 10800 # SQL port number.
          - containerPort: 10900 # Thin clients port number.
          - containerPort: 8080 # REST API
        volumeMounts:
        - mountPath: /etc/apache-ignite/config/ignite-config.xml
          name: ignite-config
          subPath: ignite-config.xml
          readOnly: true
        - mountPath: /apache-ignite
          name: ignite-disk-dev-02
        resources:
          limits:
            memory: 2500Mi
          requests:
            memory: 1000Mi    
              #Health Status
        livenessProbe:
          httpGet:
            path: /status
            port: restport-ig
          initialDelaySeconds: 1000
          periodSeconds: 50
      hostname: ignite
      restartPolicy: Always
      imagePullSecrets:
        - name: mojix-registry